// for simplicity's sake, set Adaptable & the AG Grid modules on the global scope
import { Adaptable } from '@adaptabletools/adaptable';
window.Adaptable = Adaptable;

window.agGridTheme = 'legacy';

// For charts
import { AgChartsEnterpriseModule } from 'ag-charts-enterprise';

import {
  LicenseManager,
  ModuleRegistry,
  ValidationModule,
  ColumnAutoSizeModule,
  PinnedRowModule,
  RowAutoHeightModule,
  RowStyleModule,
  CellStyleModule,
  TooltipModule,
  TextFilterModule,
  NumberFilterModule,
  DateFilterModule,
  CustomFilterModule,
  ExternalFilterModule,
  QuickFilterModule,
  RowSelectionModule,
  TextEditorModule,
  LargeTextEditorModule,
  SelectEditorModule,
  NumberEditorModule,
  DateEditorModule,
  CheckboxEditorModule,
  CustomEditorModule,
  LocaleModule,
  CsvExportModule,
  GridStateModule,
  ColumnApiModule,
  RowApiModule,
  CellApiModule,
  ScrollApiModule,
  RenderApiModule,
  EventApiModule,
  ClientSideRowModelApiModule,
  ClientSideRowModelModule,
  FindModule,
  CellSelectionModule,
  RichSelectModule,
  RowGroupingModule,
  RowGroupingPanelModule,
  GroupFilterModule,
  TreeDataModule,
  MasterDetailModule,
  SideBarModule,
  ColumnsToolPanelModule,
  FiltersToolPanelModule,
  ColumnMenuModule,
  ContextMenuModule,
  StatusBarModule,
  ExcelExportModule,
  ClipboardModule,
  SparklinesModule,
  IntegratedChartsModule,
} from 'ag-grid-enterprise';

const modules = [
  ValidationModule,
  ColumnAutoSizeModule,
  PinnedRowModule,
  RowAutoHeightModule,
  RowStyleModule,
  CellStyleModule,
  TooltipModule,
  TextFilterModule,
  NumberFilterModule,
  DateFilterModule,
  CustomFilterModule,
  ExternalFilterModule,
  QuickFilterModule,
  RowSelectionModule,
  TextEditorModule,
  LargeTextEditorModule,
  SelectEditorModule,
  NumberEditorModule,
  DateEditorModule,
  CheckboxEditorModule,
  CustomEditorModule,
  LocaleModule,
  CsvExportModule,
  GridStateModule,
  ColumnApiModule,
  RowApiModule,
  CellApiModule,
  ScrollApiModule,
  RenderApiModule,
  EventApiModule,
  ClientSideRowModelApiModule,
  ClientSideRowModelModule,
  FindModule,
  CellSelectionModule,
  RichSelectModule,
  RowGroupingModule,
  RowGroupingPanelModule,
  GroupFilterModule,
  TreeDataModule,
  MasterDetailModule,
  SideBarModule,
  ColumnsToolPanelModule,
  FiltersToolPanelModule,
  ColumnMenuModule,
  ContextMenuModule,
  StatusBarModule,
  ExcelExportModule,
  ClipboardModule,
  SparklinesModule.with(AgChartsEnterpriseModule),
  IntegratedChartsModule.with(AgChartsEnterpriseModule),
];

window.agGridModules = modules;
window.LicenseManager = LicenseManager;
